name: Test
on: [ push ]
jobs:

  test:
    strategy:
      matrix:
        os: [ windows-latest ] # list of os: https://github.com/actions/virtual-environments
        go: [ '1.16' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: checkout submodule
        run: |
          git submodule update --force --recursive --init --remote

      - name: mingw
        run: |
          choco upgrade mingw cmake git -y --no-progress
          cd mdbx/dist
          cmake -G "MinGW Makefiles" . -D CMAKE_MAKE_PROGRAM:PATH=C:\ProgramData\chocolatey\bin\make.exe -D MDBX_BUILD_SHARED_LIBRARY:BOOL=ON -D MDBX_WITHOUT_MSVC_CRT:BOOOL=OFF -D CMAKE_C_FLAGS:STRING="-Wno-unused-variable -Wno-unused-parameter -Wno-unused-function" -D CMAKE_CXX_FLAGS:STRING="-Wno-unused-variable -Wno-unused-parameter -Wno-unused-function"
          cmake --build .
          cp libmdbx.dll C:/WINDOWS/SYSTEM32/
          cd ./..
          go build .
          go test -v .

#https://github.com/golang/go/issues/20982
