name: Test
on: [ push ]
jobs:

  test:
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15 ] # list of os: https://github.com/actions/virtual-environments
        go: [ '1.16', '1.13' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go-${{ matrix.os }}-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}

      - name: Test
        run: make test

      - name: Race
        run: make race

  win:
    strategy:
      matrix:
        os: [ windows-2019 ] # list of os: https://github.com/actions/virtual-environments
        go: [ '1.16' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: mingw
        run: |
          choco upgrade mingw cmake git -y --no-progress
          go build .
          go test -v .
